name: build-and-test

env:
  configuration: release
  project_file: kaprekars.constant.core/kaprekars.constant.core.csproj
  project_test_file: kaprekars.constant.tests/kaprekars.constant.tests.csproj
  output_path: app/publish

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: restore
      run: dotnet restore ${{ env.project_file }}
      
    - name: build
      run: dotnet build -c ${{ env.configuration }} ${{env.project_file }} --no-restore 

    - name: publish
      run: dotnet publish -c ${{ env.configuration }} -o ${{ env.output_path }}

    - name: docker build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: gkama/kaprekars-constant:latest

  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: test
      run: dotnet test -c ${{ env.configuration }} ${{ env.project_test_file }} -l trx -v normal --no-build

    - name: sonarcloud scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}